routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
//Route::get('/', 'Blog\PostController@index')->name('blog');  //todo: check why FORBIDDEN
Route::get('/', 'Blog\PostController@sview')->name('search');


Route::group(['namespace' => 'Blog', 'prefix' => 'blog'], function() {
//    $methods = ['index', 'edit', 'update', 'create', 'store'];
    Route::resource('posts', 'PostController')->names('blog.posts');
    Route::resource('categories', 'CategoryController')->names('blog.categories');
});

//Route::resource('rest', 'RestTestController')->names('restTest');

Route::get('/home', 'Blog\PostController@index')->name('home');

Route::group(['prefix' => 'digging_deeper'], function() {
    Route::get('collections', 'DiggingDeeperController@collections')
        ->name('digging_deeper.collections');
});

$groupData = [
    'namespace' => 'Blog\Admin',
    'prefix'    => 'admin/blog'
];
Route::group($groupData, function() {
    $methods = ['index', 'edit', 'update', 'create', 'store'];
    Route::resource('categories', 'CategoryController')
        ->only($methods)
        ->names('blog.admin.categories');

    Route::resource('posts', 'PostController')
        ->except(['show'])
        ->names('blog.admin.posts');
});

/*routes for News*/
//Route::group(['prefix' => 'news'], function () {
//    Route::get('data', 'NewsController@data')->name('news.data');
//    Route::get('{news}/delete', 'NewsController@destroy')->name('news.delete');
//    Route::get('{news}/confirm-delete', 'NewsController@getModalDelete')->name('news.confirm-delete');
//});
//Route::resource('news', 'NewsController');

app/Http/Controllers/Blog/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Blog\Admin;

use App\Http\Controllers\Blog\Admin\BaseController as AdminBaseController;
use App\Http\Requests\BlogCategoryCreateRequest;
use App\Http\Requests\BlogCategoryUpdateRequest;
use App\Models\BlogCategory;
use App\Repositories\BlogCategoryRepository;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Str;
//use Redis;

use Illuminate\Support\Facades\Redis;

class CategoryController extends AdminBaseController
{
    /**
     * @var BlogCategoryRepository
     */
    private $blogCategoryRepository;

    public function __construct()
    {
        parent::__construct();
        $this->blogCategoryRepository = app(BlogCategoryRepository::class);
    }

    /**
     * Display a listing of the resource.
     * @return \Illuminate\Http\Response
     * @throws \Psr\SimpleCache\InvalidArgumentException
     */
    public function index()
    {


//        Cache::put('123', serialize($this->index), 150);
//        $cache = Cache::get('123');
//        dd($cache);


        $page = request()->has('page') ? request()->get('page') : 1;
        //notice: redis??
//        if (!Redis::exists('categories:' . $page)) {
//            Redis::set('categories:' . $page, \Opis\Closure\serialize($this->blogCategoryRepository->getAllWithPaginate(25)));
//        }
//        $paginator = \Opis\Closure\unserialize(Redis::get('categories:' . $page));
//        $paginator = $this->blogCategoryRepository->getAllWithPaginate(25);

        //notice: wt cache?
        $paginator = Cache::remember('category_paginator_' . $page, 15, function() {
            return $this->blogCategoryRepository->getAllWithPaginate(25);
        });

        return view('blog.admin.categories.index', compact('paginator'));
    }

    /**
     * Show the form for creating a new resource.
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
//        $category = new BlogCategory();
        $category = BlogCategory::make();
//        $categoryList = BlogCategory::all();
        $categoryList = $this->blogCategoryRepository->getForComboBox();

        return view('blog.admin.categories.edit', compact('category', 'categoryList'));
//        dd(__METHOD__);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(BlogCategoryCreateRequest $request)
    {
        $data = $request->input();
        if (empty($data['slug'])) {
            $data['slug'] = Str::slug($data['title']);
        }

//        $item = new BlogCategory($data);
        $item = BlogCategory::create($data);
        $item->save();

        //$item = (new BlogCategory())->create($data)); NOTE|NOTICE: another way to save model

        if ($item) {
            return redirect()->route('blog.admin.categories.edit', [$item->id])
                ->with(['success' => 'Successfully saved']);
        } else {
            return back()->withErrors(['msg' => 'Error with saving'])
                ->withInput();
        }
    }

    /**
     * @param                        $id
     * @param BlogCategoryRepository $categoryRepository
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
//        $category = BlogCategory::findOrFail($id);
//        $categoryList = BlogCategory::all();

        $category = $this->blogCategoryRepository->getEdit($id);
        if (empty($category)) {
            abort(404);
        }
        $categoryList = $this->blogCategoryRepository->getForComboBox();

        return view('blog.admin.categories.edit',
            compact('category', 'categoryList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param BlogCategoryUpdateRequest $request
     * @param int                      $id
     *
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(BlogCategoryUpdateRequest $request, $id)
    {
//        $validatedData = $this->validate($request, $rules);
//        dd($validatedData);
//        $item = BlogCategory::find($id);
        $item = $this->blogCategoryRepository->getEdit($id);

        if (empty($item) || is_null($item)) {
            return back()
                ->withErrors(['msg' => "Record with id: {$id} not found"])
                ->withInput();
        }

        $data = $request->all();

        //notice moved to observer
//        if (empty($data['slug'])) {
//            $data['slug'] = Str::slug($data['title']);
//        }

        $result = $item->update($data);
//            ->fill($data)
//            ->save();

        if ($result) {
            return redirect()
                ->route('blog.admin.categories.edit', $item->id)
                ->with(['success' => 'Saved successfully']);
        } else {
            return back()
                ->withErrors(['msg' => "Error with saving"])
                ->withInput();
        }
    }
}

app/Http/Controllers/Blog/CategoryController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Http\Controllers\Blog\Admin\BaseController as AdminBaseController;
use App\Http\Controllers\Blog\BaseController;
use App\Http\Requests\BlogCategoryCreateRequest;
use App\Http\Requests\BlogCategoryUpdateRequest;
use App\Models\BlogCategory;
use App\Repositories\BlogCategoryRepository;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Str;

class CategoryController extends BaseController
{
    /**
     * @var BlogCategoryRepository
     */
    private $blogCategoryRepository;

    public function __construct()
    {
        $this->blogCategoryRepository = app(BlogCategoryRepository::class);
    }

    /**
     * Display a listing of the resource.
     * @return \Illuminate\Http\Response
     * @throws \Psr\SimpleCache\InvalidArgumentException
     */
    public function index()
    {


        $page = request()->has('page') ? request()->get('page') : 1;

        $paginator = Cache::remember('category_paginator_' . $page, 15, function() {
            return $this->blogCategoryRepository->getAllWithPaginate(25);
        });

        return view('blog.categories.index', compact('paginator'));
    }

    /**
     * Show the form for creating a new resource.
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
//        $category = new BlogCategory();
        $category = BlogCategory::make();
//        $categoryList = BlogCategory::all();
        $categoryList = $this->blogCategoryRepository->getForComboBox();

        return view('blog.admin.categories.edit', compact('category', 'categoryList'));
//        dd(__METHOD__);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(BlogCategoryCreateRequest $request)
    {
        $data = $request->input();
        if (empty($data['slug'])) {
            $data['slug'] = Str::slug($data['title']);
        }

//        $item = new BlogCategory($data);
        $item = BlogCategory::create($data);
        $item->save();

        //$item = (new BlogCategory())->create($data)); NOTE|NOTICE: another way to save model

        if ($item) {
            return redirect()->route('blog.admin.categories.edit', [$item->id])
                ->with(['success' => 'Successfully saved']);
        } else {
            return back()->withErrors(['msg' => 'Error with saving'])
                ->withInput();
        }
    }

    /**
     * @param                        $id
     * @param BlogCategoryRepository $categoryRepository
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
//        $category = BlogCategory::findOrFail($id);
//        $categoryList = BlogCategory::all();

        $category = $this->blogCategoryRepository->getEdit($id);
        if (empty($category)) {
            abort(404);
        }
        $categoryList = $this->blogCategoryRepository->getForComboBox();

        return view('blog.admin.categories.edit',
            compact('category', 'categoryList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param BlogCategoryUpdateRequest $request
     * @param int                      $id
     *
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(BlogCategoryUpdateRequest $request, $id)
    {
//        $validatedData = $this->validate($request, $rules);
//        dd($validatedData);
//        $item = BlogCategory::find($id);
        $item = $this->blogCategoryRepository->getEdit($id);

        if (empty($item) || is_null($item)) {
            return back()
                ->withErrors(['msg' => "Record with id: {$id} not found"])
                ->withInput();
        }

        $data = $request->all();

        //notice moved to observer
//        if (empty($data['slug'])) {
//            $data['slug'] = Str::slug($data['title']);
//        }

        $result = $item->update($data);
//            ->fill($data)
//            ->save();

        if ($result) {
            return redirect()
                ->route('blog.admin.categories.edit', $item->id)
                ->with(['success' => 'Saved successfully']);
        } else {
            return back()
                ->withErrors(['msg' => "Error with saving"])
                ->withInput();
        }
    }
}

resources/views/blog/admin/categories/edit.blade.php
@extends('layouts.app')

@section('content')
    @php /**  @var \App\Models\BlogCategory $category  */ @endphp
{{--    <form method="POST" action="{{route('blog.admin.categories.update', $category->id)}}">--}}
        @if($category->exists)
            <form method="POST" action="{{route('blog.admin.categories.update', $category->id)}}">
            @method('PATCH')
        @else
            <form method="POST" action="{{route('blog.admin.categories.store')}}">
        @endif
        @csrf
        <div class="container">
            @php
                /** @var \Illuminate\Support\ViewErrorBag $errors */
            @endphp
            @if($errors->any())
                <div class="row justify-content-center">
                    <div class="col-md-11">
                        <div class="alert alert-danger" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                                <span aria-hidden="true">x</span>
                            </button>
                            {{$errors->first()}}
                        </div>
                    </div>
                </div>
            @endif
            @if(session('success'))
                <div class="row justify-content-center">
                    <div class="col-md-11">
                        <div class="alert alert-success" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                                <span aria-hidden="true">x</span>
                            </button>
                            {{session()->get('success')}}
                        </div>
                    </div>
                </div>
            @endif
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @include('blog.admin.categories.includes.item_edit_main_col')
                </div>
                <div class="col-md-3">
                    @include('blog.admin.categories.includes.item_edit_add_col')
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/blog/admin/categories/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
                    <a class="btn btn-primary" href="{{route('blog.admin.categories.create')}}">Add category</a>
                </nav>
                <div class="card">
{{--                    <div class="card-header">Dashboard</div>--}}

                    <div class="card-body">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Category</th>
                                <th>Parent</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($paginator as $category)
                                @php /** @var \App\Models\BlogCategory @category */ @endphp
                                <tr>
                                    <td>{{$category->id}}</td>
                                    <td>
                                        <a href="{{route('blog.admin.categories.edit', $category->id)}}">
                                            {{$category->title}}
                                        </a>
                                    </td>
                                    <td @if(in_array($category->parent_id, [0, 1])) style="color: #ccc;" @endif>
{{--                                        {{$category->parent_id}}--}}
{{--                                        {{$category->parentCategory->title ?? '?'}} //notice: the same 1--}}
{{--                                        {{optional($category->parentCategory)->title}} //notice: the same 1--}}

                                        {{-- notice: other variant 2--}}
{{--                                        {{--}}
{{--                                            $category->parentCategory->title--}}
{{--                                                ?? ($category->id === \App\Models\BlogCategory::ROOT--}}
{{--                                                    ? 'Root'--}}
{{--                                                    : '???')--}}
{{--                                        }}--}}
                                        {{-- notice: accessors/mutators--}}

                                        {{$category->parentTitle}}


                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        @if($paginator->total() > $paginator->count())
            <br />
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="card">
                         <div class="card-body">
                            {{$paginator->links()}}
                         </div>
                    </div>
                </div>
            </div>
        @endif
    </div>
@endsection