routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
//Route::get('/', 'Blog\PostController@index')->name('blog');  //todo: check why FORBIDDEN
Route::get('/', 'Blog\PostController@sview')->name('search');


Route::group(['namespace' => 'Blog', 'prefix' => 'blog'], function() {
//    $methods = ['index', 'edit', 'update', 'create', 'store'];
    Route::resource('posts', 'PostController')->names('blog.posts');
    Route::resource('categories', 'CategoryController')->names('blog.categories');
});

//Route::resource('rest', 'RestTestController')->names('restTest');

Route::get('/home', 'Blog\PostController@index')->name('home');

Route::group(['prefix' => 'digging_deeper'], function() {
    Route::get('collections', 'DiggingDeeperController@collections')
        ->name('digging_deeper.collections');
});

$groupData = [
    'namespace' => 'Blog\Admin',
    'prefix'    => 'admin/blog'
];
Route::group($groupData, function() {
    $methods = ['index', 'edit', 'update', 'create', 'store'];
    Route::resource('categories', 'CategoryController')
        ->only($methods)
        ->names('blog.admin.categories');

    Route::resource('posts', 'PostController')
        ->except(['show'])
        ->names('blog.admin.posts');
});

/*routes for News*/
//Route::group(['prefix' => 'news'], function () {
//    Route::get('data', 'NewsController@data')->name('news.data');
//    Route::get('{news}/delete', 'NewsController@destroy')->name('news.delete');
//    Route::get('{news}/confirm-delete', 'NewsController@getModalDelete')->name('news.confirm-delete');
//});
//Route::resource('news', 'NewsController');

app/Http/Controllers/Blog/Admin/PostController.php
<?php

namespace App\Http\Controllers\Blog\Admin;

use App\Http\Requests\BlogPostCreateRequest;
use App\Http\Requests\BlogPostUpdateRequest;
use App\Models\BlogPost;
use App\Repositories\BlogCategoryRepository;
use App\Repositories\BlogPostRepository;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Redis;
use App\Http\Requests;
use Illuminate\Support\Facades\Request;

class PostController extends BaseController
{

    /**
     * @var BlogPostRepository|\Illuminate\Contracts\Foundation\Application|mixed
     */
    private $blogPostRepository;

    /**
     * @var BlogCategoryRepository|\Illuminate\Contracts\Foundation\Application|mixed
     */
    private $blogCategoryRepository;

    /**
     * PostController constructor.
     */
    public function __construct()
    {
        parent::__construct();

        $this->middleware('auth');

        $this->blogPostRepository = app(BlogPostRepository::class);
        $this->blogCategoryRepository = app(BlogCategoryRepository::class);
    }

    /**
     * Display a listing of the resource.
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $page = request()->has('page') ? request()->get('page') : 1;
//        if (!Redis::exists('posts:' . $page)) {
//            Redis::set('posts:' . $page, \Opis\Closure\serialize($this->blogPostRepository->getAllWithPaginate()));
//        }
//        $paginator = \Opis\Closure\unserialize(Redis::get('posts:' . $page));

        $paginator = Cache::remember('post_paginator_' . $page, 15, function() {
            return $paginator = $this->blogPostRepository->getAllWithPaginate(25);
        });
//        $paginator = $this->blogPostRepository->getAllWithPaginate();

        return view('blog.admin.posts.index', compact('paginator'));
    }

    /**
     * Show the form for creating a new resource.
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
//        $post = new BlogPost();
        $post = BlogPost::make();
        $categoryList = $this->blogCategoryRepository->getForComboBox();

        return view('blog.admin.posts.edit', compact('post', 'categoryList'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(BlogPostCreateRequest $request)
    {
        $data = $request->input();
//        $post = (new BlogPost())->create($data);
        $post = BlogPost::create($data);

        if ($post) {
            return redirect()->route('blog.admin.posts.edit', [$post->id])->with(['success' => 'Saved successfully']);
        } else {
            return back()->withErrors(['msg' => 'Error with saving'])->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        dd(__METHOD__, $id);
    }

    /**
     * @param int $id
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $post = $this->blogPostRepository->getEdit($id);
        if (empty($post)) {
            abort(404);
        }

        $categoryList = $this->blogCategoryRepository->getForComboBox();

        return view('blog.admin.posts.edit',
            compact('post', 'categoryList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(BlogPostUpdateRequest $request, $id)
    {
        $post = $this->blogPostRepository->getEdit($id);

        if (empty($post)) {
            return back()->withErrors(['msg' => "Record #{$id} not found"])->withInput();
        }

        $data = $request->all();

        /**
         * notice moved to observer @BlogPostObserver::setPublishedAt() | @BlogPostObserver::setSlug()
         */
//        if (empty($data['slug'])) {
//            $data['slug'] = Str::slug($data['title']);
//        }
//        if (empty($post->published_at) && $data['is_published']) {
//            $data['published_at'] = Carbon::now();
//        }

        $result = $post->update($data);

        if ($result) {
            return redirect()
                ->route('blog.admin.posts.edit', $post->id)
                ->with(['success' => 'Successfully saved']);
        } else {
            return back()
                ->withErrors(['msg' => 'Error with saving'])
                ->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = BlogPost::destroy($id);
//        dd(__METHOD__, request()->all(), $id);

        if ($result) {
            return redirect()
                ->route('blog.admin.posts.index')
                ->with(['success' => "Record with id: {$id} was deleted"]);
        } else {
            return back()->withErrors(['msg' => 'Error with deleting']);
        }
    }
}

app/Http/Controllers/Blog/PostController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Models\BlogPost;
use App\Events\SearchEvent;
use App\Repositories\BlogCategoryRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use App\Repositories\BlogPostRepository;

class PostController extends BaseController
{
    /**
     * @var BlogPostRepository|\Illuminate\Contracts\Foundation\Application|mixed
     */
    private $blogPostRepository;

    /**
     * @var BlogCategoryRepository|\Illuminate\Contracts\Foundation\Application|mixed
     */
    private $blogCategoryRepository;


    /**
     * PostController constructor.
     */
    public function __construct()
    {
        $this->blogPostRepository = app(BlogPostRepository::class);
        $this->blogCategoryRepository = app(BlogCategoryRepository::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $page = request()->has('page') ? request()->get('page') : 1;

        $paginator = Cache::remember('post_paginator_' . $page, 15, function() {
            return $this->blogPostRepository->getAllWithPaginate(25);
        });

        return view('blog.posts.index', compact('paginator'));
    }

    public function search(Request $request)
    {
        $query = $request->query('query');
//        return response()->json($query);
        $products = BlogPost::where('title', 'like', '%' . $query . '%')
//            ->orWhere('description', 'like', '%' . $query . '%')
            ->get();

//        return response()->json($products);
        //broadcast search results with Pusher channels
        event(new SearchEvent($products));

//        return response()->json($products);
        return response()->json("ok");
    }

    public function sview()
    {
        return view('search');
    }

    //fetch all products
    public function get(Request $request)
    {
        $products = BlogPost::all();
        return response()->json($products);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/blog/admin/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    @php /**  @var \App\Models\BlogPost $post  */ @endphp

        <div class="container">
            @include('blog.admin.posts.includes.result_messages')
            @if($post->exists)
                <form method="POST" action="{{route('blog.admin.posts.update', $post->id)}}">
                    @method('PATCH')
            @else
                <form method="POST" action="{{route('blog.admin.posts.store')}}">
            @endif
            @csrf
                    <div class="row justify-content-center">
                        <div class="col-md-8">
                            @include('blog.admin.posts.includes.post_edit_main_col')
                        </div>
                        <div class="col-md-3">
                            @include('blog.admin.posts.includes.post_edit_add_col')
                        </div>
                    </div>
                </form>
                @if($post->exists)
                    <br />
                    <form method="POST" action="{{route('blog.admin.posts.destroy', $post->id)}}">
                        @method('DELETE')
                        @csrf
                        <div class="row justify-content-center">
                            <div class="col-md-8">
                                <div class="card">
                                    <div class="card-body">
                                        <button type="submit" class="btn btn-link">Delete</button>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                    </form>
                @endif
        </div>
@endsection

resources/views/blog/admin/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <!-- todo: ADD RESTORE LINK -->
        @include('blog.admin.posts.includes.result_messages')
        <div class="row justify-content-center">
            <div class="col-md-12">
                <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
                    <a class="btn btn-primary" href="{{route('blog.admin.posts.create')}}">Add Post</a>
                </nav>
                <div class="card">
                    <div class="card-body">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Author</th>
                                <th>Category</th>
                                <th>Title</th>
                                <th>Publish date</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($paginator as $post)
                                @php /** @var \App\Models\BlogPost $post */ @endphp
                                <tr @if(!$post->is_published) style="background-color: #ccc;" @endif>
                                    <td>{{$post->id}}</td>
                                    <td>{{$post->user->name}}</td>
                                    <td>{{$post->category->title}}</td>
                                    <td>
                                        <a href="{{route('blog.admin.posts.edit', $post->id)}}">
                                            {{$post->title}}
                                        </a>
                                    </td>
                                    <td>{{$post->published_at ? \Carbon\Carbon::parse($post->published_at)->format('d.M H:i') : ''}}</td>
                                </tr>
                            @endforeach
                            </tbody>
                            <tfoot></tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        @if($paginator->total() > $paginator->count())
            <br />
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            {{$paginator->links()}}
                        </div>
                    </div>
                </div>
            </div>
        @endif
    </div>

@endsection

resources/views/blog/admin/posts/search.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <meta name="csrf-token" content="{{ csrf_token() }}">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
          integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    {{--bxslider--}}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css"/>

    <link rel="stylesheet" href="{{mix('css/app.css')}}">
    <title>Realtime search engine with Pusher and Laravel</title>
</head>
<body>


<div id="app">

    <div class="container">
        <h5 class="text-center" style="margin-top: 32px">Realtime search engine with Laravel and Pusher</h5>
        <br><br>
        <searchbar></searchbar>
        <products></products>
    </div>

</div>

<script async src="{{mix('js/app.js')}}"></script>

</body>

</html>